spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
    # Base Local
    url: jdbc:postgresql://localhost:5432/comprando_en_casa?createDatabaseIfNotExist=true
    username: postgres
    password: postgres

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug